version: 2
jobs:
    build:
        docker:
            - image: docker:17.07.0-ce-git
        steps:
            - checkout
            - setup_remote_docker:
                version: 17.07.0-ce
            - run:
                name: Build docker image
                command: docker build -t u6kapps/sample-circleci-2.0 .
            - run:
                name: Test docker image
                command: docker run u6kapps/sample-circleci-2.0
            - run:
                name: Save docker image
                command: |
                    mkdir -p ~/caches
                    docker save u6kapps/sample-circleci-2.0 -o ~/caches/image.tar
            - save_cache:
                key: docker-{{ .Revision }}
                paths:
                    - ~/caches/image.tar
    push:
        docker:
            - image: docker:17.07.0-ce-git
        steps:
            - checkout
            - setup_remote_docker:
                version: 17.07.0-ce
            - restore_cache:
                key: docker-{{ .Revision }}
                paths:
                    - ~/caches/image.tar
            - run:
                name: Load docker image
                command: docker load -i ~/caches/image.tar
            - run:
                name: Push docker image
                command: |
                    TAG=`git describe --abbrev=0`
                    docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
                    docker tag u6kapps/sample-circleci-2.0 u6kapps/sample-circleci-2.0:${TAG}
                    docker push u6kapps/sample-circleci-2.0
workflows:
    version: 2
    build-and-push:
        jobs:
            - build
            - push:
                requires:
                    - push
                filters:
                    branches:
                        only: master