version: 2
jobs:
    build:
        working_directory: ~/build
        docker:
            - image: docker:17.07.0-ce
        steps:
            - checkout
            - run: echo "hello world"