version: 2
jobs:
    build:
        docker:
            - image: docker:17.07.0-ce
        steps:
            - checkout
            - setup_remote_docker:
                version: 17.07.0-ce
            - run:
                name: Build docker image
                command: docker build -t u6kapps/sample-circleci-2.0 .
            - run:
                name: Save docker image
                command: |
                    mkdir -p ~/caches
                    docker save u6kapps/sample-circleci-2.0 -o ~/caches/image.tar
            - save_cache:
                key: docker-{{ .Revision }}
                paths:
                    - ~/caches/image.tar
    test:
        docker:
            - image: docker:17.07.0-ce
        steps:
            - checkout
            - setup_remote_docker:
                version: 17.07.0-ce
            - restore_cache:
                key: docker-{{ .Revision }}
                paths:
                    - ~/caches/image.tar
            - run:
                name: Load docker image
                command: docker load -i ~/caches/image.tar
            - run:
                name: Test docker image
                command: docker run --rm u6kapps/sample-circleci-2.0
    push:
        docker:
            - image: docker:17.07.0-ce
        steps:
            - checkout
            - setup_remote_docker:
                version: 17.07.0-ce
            - restore_cache:
                key: docker-{{ .Revision }}
                paths:
                    - ~/caches/image.tar
            - run:
                name: Load docker image
                command: docker load -i ~/caches/image.tar
            - run:
                name: Push docker image
                command: |
                    echo ${CIRCLE_TAG}
                    env
workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build
            - test:
                requires:
                    - build
            - push:
                requires:
                    - test
                filters:
                    tags:
                        only: /.*/